version: "1.0"

services:
    web:
        restart: always
        image: go-postgres-web-api
        ports:
            - 8080:8080
        environment:
            - "DB_PORT=5432"
            - "DB_HOST=postgres-host"
            - "DB_NAME=db-name"
            - "DB_PASS=1234"
